import type { QiitaArticleResponse } from '../types'

export const successData: QiitaArticleResponse = [
  {
    renderedBody: 'renderedBody',
    body: 'body',
    coediting: false,
    commentsCount: 0,
    createdAt: '2024-02-23T12:19:21+09:00',
    id: '934a100cb129ac63aa31',
    likesCount: 0,
    private: false,
    reactionsCount: 0,
    stocksCount: 0,
    tags: [{ name: 'HTML' }, { name: 'CSS' }, { name: 'Web' }],
    title: 'CSSのhasを使ってみたかっただけ',
    updatedAt: '2024-02-23T12:19:21+09:00',
    url: 'https://qiita.com/koto74/items/934a100cb129ac63aa31',
    user: {
      description: '',
      facebookId: '',
      followeesCount: 1,
      followersCount: 3,
      githubLoginName: 'koto74',
      id: 'koto74',
      itemsCount: 3,
      linkedinId: '',
      location: '',
      name: '',
      organization: '',
      permanentId: 3289992,
      profileImageUrl: 'https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/3289992/profile-images/1707318925',
      teamOnly: false,
      twitterScreenName: 'kotoganaiyo',
      websiteUrl: ''
    },
    pageViewsCount: null,
    teamMembership: null,
    organizationUrlName: null,
    slide: false
  },
  {
    renderedBody: 'renderedBody',
    body: 'body',
    coediting: false,
    commentsCount: 0,
    createdAt: '2024-02-23T11:07:34+09:00',
    id: '5d788b10ec8939ed3474',
    likesCount: 0,
    private: false,
    reactionsCount: 0,
    stocksCount: 0,
    tags: [{ name: 'Databricks' }, { name: 'clip' }, { name: 'LlamaIndex' }, { name: 'GPT4V' }],
    title: 'CLIPエンべディングを用いた画像による画像検索およびGPT4Vを用いた画像関連性の理由づけ',
    updatedAt: '2024-02-23T11:09:43+09:00',
    url: 'https://qiita.com/takaYayoi/items/5d788b10ec8939ed3474',
    user: {
      description: 'Databricksのマネージャ、ソリューションアーキテクトです。こちらでDatabricks/Spark関連の情報をシェアできたらと考えています。',
      facebookId: 'takaaki.yayoi',
      followeesCount: 11,
      followersCount: 315,
      githubLoginName: 'taka-yayoi',
      id: 'takaYayoi',
      itemsCount: 1410,
      linkedinId: 'takaaki-yayoi',
      location: 'Tokyo',
      name: 'Takaaki Yayoi',
      organization: 'Databricks',
      permanentId: 1168882,
      profileImageUrl: 'https://lh3.googleusercontent.com/a-/AOh14GiHDumucs3o6fmzfrEsScv2xRCHlOlUpn5zNq5u=s50',
      teamOnly: false,
      twitterScreenName: 'takaAki',
      websiteUrl: 'https://databricks.com/jp/'
    },
    pageViewsCount: null,
    teamMembership: null,
    organizationUrlName: 'databricks',
    slide: false
  },
  {
    renderedBody: 'renderedBody',
    body: 'body',
    coediting: false,
    commentsCount: 0,
    createdAt: '2024-02-23T08:15:24+09:00',
    id: '7e538787f6279547a197',
    likesCount: 0,
    private: false,
    reactionsCount: 0,
    stocksCount: 0,
    tags: [{ name: 'API' }],
    title: 'Google Maps APIについて',
    updatedAt: '2024-02-23T08:15:24+09:00',
    url: 'https://qiita.com/yamazaki25/items/7e538787f6279547a197',
    user: {
      description: 'JPT 10月入社/Web系/日々の学びを投稿しています。いいねを押してもらえると励みになります。',
      facebookId: '',
      followeesCount: 0,
      followersCount: 6,
      githubLoginName: 'yamazaki-hidekuni',
      id: 'yamazaki25',
      itemsCount: 148,
      linkedinId: '',
      location: '',
      name: '',
      organization: '',
      permanentId: 3571999,
      profileImageUrl: 'https://s3-ap-northeast-1.amazonaws.com/qiita-image-store/0/3571999/10c210fe408c2492b4d760e94c330fec5ecdec5d/large.png?1696601539',
      teamOnly: false,
      twitterScreenName: null,
      websiteUrl: ''
    },
    pageViewsCount: null,
    teamMembership: null,
    organizationUrlName: null,
    slide: false
  },
  {
    renderedBody: 'renderedBody',
    body: 'body',
    coediting: false,
    commentsCount: 0,
    createdAt: '2024-02-23T01:46:45+09:00',
    id: '52fd42996286c04d7c51',
    likesCount: 0,
    private: false,
    reactionsCount: 0,
    stocksCount: 0,
    tags: [{ name: 'Python' }, { name: 'plotly' }, { name: 'ChatGPT' }, { name: 'Pydataset' }],
    title: 'ChatGPTとPythonで学ぶ plotly と pydataset',
    updatedAt: '2024-02-23T01:46:45+09:00',
    url: 'https://qiita.com/maskot1977/items/52fd42996286c04d7c51',
    user: {
      description: '大学や大学院等で機械学習やプログラミングの講義をしております。ご興味のある方はお声がけください。',
      facebookId: '',
      followeesCount: 78,
      followersCount: 412,
      githubLoginName: 'maskot1977',
      id: 'maskot1977',
      itemsCount: 318,
      linkedinId: 'masaaki-kotera-8699b814/',
      location: '',
      name: 'Ikemen Mas Kot',
      organization: '',
      permanentId: 211162,
      profileImageUrl: 'https://s3-ap-northeast-1.amazonaws.com/qiita-image-store/0/211162/2c595ae6fa3935f290b29241a8947c41dd71f6df/xLarge.png?1702603155',
      teamOnly: false,
      twitterScreenName: 'HandsomeKinoko',
      websiteUrl: 'https://scholar.google.com/citations?user=UVyoQ7YAAAAJ\u0026hl=ja'
    },
    pageViewsCount: null,
    teamMembership: null,
    organizationUrlName: null,
    slide: false
  },
  {
    renderedBody: 'renderedBody',
    body: 'body',
    coediting: false,
    commentsCount: 0,
    createdAt: '2024-02-23T01:04:54+09:00',
    id: '0ac033f54cfc5969f8cd',
    likesCount: 0,
    private: false,
    reactionsCount: 0,
    stocksCount: 0,
    tags: [
      {
        name: 'JavaScript'
      },
      {
        name: 'mediawiki'
      },
      {
        name: 'Miraheze'
      }
    ],
    title: 'テンプレートをIMG loading=lazyのような遅延読み込みさせる',
    updatedAt: '2024-02-23T08:30:45+09:00',
    url: 'https://qiita.com/Urushibara01/items/0ac033f54cfc5969f8cd',
    user: {
      description: null,
      facebookId: null,
      followeesCount: 1,
      followersCount: 31,
      githubLoginName: 'Urushibara',
      id: 'Urushibara01',
      itemsCount: 68,
      linkedinId: null,
      location: null,
      name: '',
      organization: null,
      permanentId: 102207,
      profileImageUrl: 'https://qiita-image-store.s3.amazonaws.com/0/102207/profile-images/1473708626',
      teamOnly: false,
      twitterScreenName: 'tsujiPneuma',
      websiteUrl: null
    },
    pageViewsCount: null,
    teamMembership: null,
    organizationUrlName: null,
    slide: false
  },
  {
    renderedBody: 'renderedBody',
    body: 'body',
    coediting: false,
    commentsCount: 0,
    createdAt: '2024-02-22T23:15:07+09:00',
    id: '545525332a47cd93a08f',
    likesCount: 0,
    private: false,
    reactionsCount: 0,
    stocksCount: 1,
    tags: [{ name: 'Python' }, { name: 'OpenCV' }, { name: '楽譜' }],
    title: 'Pythonで楽譜付き演奏動画から楽譜を作る',
    updatedAt: '2024-02-22T23:15:07+09:00',
    url: 'https://qiita.com/lionreo00/items/545525332a47cd93a08f',
    user: {
      description: '2004生まれ\r\n学校を卒業してから、趣味でプログラミングをしている素人',
      facebookId: '',
      followeesCount: 3,
      followersCount: 0,
      githubLoginName: null,
      id: 'lionreo00',
      itemsCount: 2,
      linkedinId: '',
      location: '',
      name: 'ぬざた',
      organization: '',
      permanentId: 3537209,
      profileImageUrl: 'https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/3537209/profile-images/1706379953',
      teamOnly: false,
      twitterScreenName: 'Reo99870770',
      websiteUrl: ''
    },
    pageViewsCount: null,
    teamMembership: null,
    organizationUrlName: null,
    slide: false
  },
  {
    renderedBody: 'renderedBody',
    body: 'body',
    coediting: false,
    commentsCount: 0,
    createdAt: '2024-02-22T22:42:44+09:00',
    id: 'bf56a612e4007f5ef5ce',
    likesCount: 0,
    private: false,
    reactionsCount: 0,
    stocksCount: 0,
    tags: [{ name: 'HTML' }, { name: 'CSS' }, { name: 'UI' }, { name: 'タグ' }],
    title: '【HTML】削除ボタン付きタグのサンプル',
    updatedAt: '2024-02-22T22:43:05+09:00',
    url: 'https://qiita.com/mogamoga1337/items/bf56a612e4007f5ef5ce',
    user: {
      description: null,
      facebookId: null,
      followeesCount: 0,
      followersCount: 16,
      githubLoginName: 'mogamoga1024',
      id: 'mogamoga1337',
      itemsCount: 128,
      linkedinId: null,
      location: null,
      name: '',
      organization: null,
      permanentId: 649673,
      profileImageUrl: 'https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/649673/profile-images/1591390534',
      teamOnly: false,
      twitterScreenName: null,
      websiteUrl: null
    },
    pageViewsCount: null,
    teamMembership: null,
    organizationUrlName: null,
    slide: false
  },
  {
    renderedBody: 'renderedBody',
    body: 'body',
    coediting: false,
    commentsCount: 0,
    createdAt: '2024-02-22T22:37:29+09:00',
    id: 'a971de668bf5538592ed',
    likesCount: 0,
    private: false,
    reactionsCount: 0,
    stocksCount: 0,
    tags: [{ name: 'JavaScript' }, { name: 'Rails' }, { name: 'jQuery' }, { name: '初心者' }, { name: 'RubyonRails6.0' }],
    title: '【Rails】RailsにJS, jQueryを実装する方法',
    updatedAt: '2024-02-22T22:37:29+09:00',
    url: 'https://qiita.com/gintaro0111/items/a971de668bf5538592ed',
    user: {
      description: '2024年1月からプログラミングの勉強開始！\r\n転職に向けて日々アウトプットの練習をしています！\r\n初心者のため、何か修正点などあれば教えていただけますと幸いです()',
      facebookId: '',
      followeesCount: 2,
      followersCount: 0,
      githubLoginName: 'Sakishima0111',
      id: 'gintaro0111',
      itemsCount: 19,
      linkedinId: '',
      location: '東京都',
      name: 'gintaro',
      organization: '',
      permanentId: 3677302,
      profileImageUrl: 'https://s3-ap-northeast-1.amazonaws.com/qiita-image-store/0/3677302/336ac5514c9fc9232172608fcc36f92acaefbe3f/xLarge.png?1707053357',
      teamOnly: false,
      twitterScreenName: null,
      websiteUrl: ''
    },
    pageViewsCount: null,
    teamMembership: null,
    organizationUrlName: null,
    slide: false
  },
  {
    renderedBody: 'renderedBody',
    body: 'body',
    coediting: false,
    commentsCount: 0,
    createdAt: '2024-02-22T22:34:17+09:00',
    id: '0d81c5b96ac5154b2544',
    likesCount: 0,
    private: false,
    reactionsCount: 0,
    stocksCount: 0,
    tags: [{ name: '電気' }, { name: '電気自動車' }, { name: '電気系ガチ素人' }, { name: '電気回路' }, { name: '電気主任技術者' }],
    title: '誘導機の諸性質',
    updatedAt: '2024-02-22T22:34:17+09:00',
    url: 'https://qiita.com/arairuca/items/0d81c5b96ac5154b2544',
    user: {
      description: '電気工学の情報を発信しています',
      facebookId: '',
      followeesCount: 1,
      followersCount: 1,
      githubLoginName: null,
      id: 'arairuca',
      itemsCount: 8,
      linkedinId: '',
      location: '',
      name: '',
      organization: '',
      permanentId: 1686019,
      profileImageUrl: 'https://pbs.twimg.com/profileImages/1327613680310132740/KaYSQr02Bigger.jpg',
      teamOnly: false,
      twitterScreenName: 'arairuca',
      websiteUrl: ''
    },
    pageViewsCount: null,
    teamMembership: null,
    organizationUrlName: null,
    slide: false
  },
  {
    renderedBody: 'renderedBody',
    body: 'body',
    coediting: false,
    commentsCount: 0,
    createdAt: '2024-02-22T21:59:49+09:00',
    id: '97c40aa3cd27046923fd',
    likesCount: 1,
    private: false,
    reactionsCount: 0,
    stocksCount: 0,
    tags: [{ name: 'イベント' }, { name: 'AI' }, { name: 'ChatGPT' }],
    title: '【イベントレポート】ChatGPT Meetup Tokyo #6',
    updatedAt: '2024-02-22T21:59:49+09:00',
    url: 'https://qiita.com/papasim824/items/97c40aa3cd27046923fd',
    user: {
      description: '子育て中のエンジニア。Pythonが好き。',
      facebookId: '',
      followeesCount: 0,
      followersCount: 9,
      githubLoginName: null,
      id: 'papasim824',
      itemsCount: 19,
      linkedinId: '',
      location: '',
      name: '',
      organization: '',
      permanentId: 649608,
      profileImageUrl: 'https://s3-ap-northeast-1.amazonaws.com/qiita-image-store/0/649608/e6ebc8d07db1a43c67927f80f4484ebdf7fba834/xLarge.png?1669202403',
      teamOnly: false,
      twitterScreenName: null,
      websiteUrl: ''
    },
    pageViewsCount: null,
    teamMembership: null,
    organizationUrlName: null,
    slide: false
  }
]

export const emptyData: QiitaArticleResponse = []
