version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '10:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 5
    target-branch: 'main'
