import type { NoteTechArticleResponse } from '../types'

/** 正常系の記事データ */
export const successData: NoteTechArticleResponse = {
  data: {
    categoryId: 1,
    firstPage: true,
    nextPage: 2,
    lastPage: false,
    notes: [
      {
        id: 81743276,
        key: 'nb66299f4a0b5',
        isTreasuredNote: false,
        body: 'wordpressの子テーマにカスタマイズしても反映されないことへの解決です。\n\n結論:\n子テーマをインストールし直すことで解決しました。\n\nCSS反映ができなかった子テーマには　style.css のファイルのみで、function.phpのファイルがありませんでした。\n\nそこで自分でfunction.php を追加してみましたが改善されず。\n\n一旦親テーマの有効化をしてみたところ、子テーマのファイルは壊れていますと表示されたため、削除しました。\n\nそして最新版？(バージョ',
        externalUrl: null,
        separator: null,
        type: 'TextNote',
        userId: 3599608,
        name: '[wordpress]子テーマのCSSが反映されない［備忘録］',
        description: null,
        tweetText: '[wordpress]子テーマのCSSが反映されない［備忘録］｜y.saito #note',
        twitterShareUrl: '/',
        facebookShareUrl: '/',
        lineShareUrl: '/',
        noteUrl: '/',
        canMultipleLimitedNote: false,
        canSellOnFirstComeNote: false,
        pictures: [],
        embeddedContents: [],
        audio: null,
        status: 'published',
        publishAt: '2024-03-02T17:07:51.000+09:00',
        price: 0,
        createdAt: '2024-03-02T17:07:15.000+09:00',
        updatedAt: '2024-03-02T17:07:51.000+09:00',
        format: '3.0',
        likeCount: 0,
        anonymousLikeCount: null,
        imageCount: 0,
        commentCount: 0,
        isLimited: false,
        isTrial: false,
        isRefund: false,
        isMembershipConnected: false,
        hasAvailableCirclePlans: false,
        isMyNote: false,
        canRead: true,
        canVote: true,
        canComment: true,
        labels: [],
        isLiked: null,
        isPurchased: false,
        isMagazinePurchased: false,
        isAvailable: false,
        spEyecatch: '/img/no-image-icon.jpg',
        hasDraft: false,
        isDraft: null,
        isPublished: true,
        isReserved: false,
        reservedPublishAt: null,
        disableComment: false,
        likes: [],
        user: {
          id: 3599608,
          urlname: 'yuukasaito',
          nickname: 'y.saito',
          noteCount: 14,
          followingCount: 3,
          followerCount: 0,
          userProfileImagePath: '/img/no-image-icon.jpg',
          createdAt: '2020-09-12T08:20:07.000+09:00',
          disableSupport: false,
          isFollowing: false,
          isMe: false,
          likeAppealText: 'ありがとう！励みになります！',
          likeAppealImage: null,
          shareAppeal: { text: null, image: null },
          magazineAddAppeal: { text: null, image: null },
          purchaseAppealTextNote: null,
          purchaseAppealTextMagazine: null,
          purchaseAppealTextSupport: null,
          followAppealText: null,
          followAppealImage: null,
          twitterNickname: null,
          customDomain: null
        },
        commentViewable: true,
        comments: [],
        hashtagNotes: [],
        hasCoupon: false,
        priorSale: null,
        customDomain: null,
        editableScopes: ['web', 'ios', 'android'],
        nonEditableReason: null
      },
      {
        id: 81728589,
        key: 'ne314a033f1a5',
        isTreasuredNote: false,
        body: 'しばらく使ってわかったこと。\nアリス配列はよく変態配列という形容詞とともに紹介されているが、このキーボードはそれほど開いていないので、使ってもそんな違和感は感じない（個人の感想です）。が、せっかくならもう少し開いた形状の方が良かったのではないかと思っている。\n\nキーボードが光ることはMacBookなどもあるので、それ自体は珍しくないが、ひかり方のバリエーションが１５種類もあり、さらにメインキーボード部分とサイド部分で光り方を変えることができる。少し暗いところで使うとはっきりわ',
        externalUrl: null,
        separator: null,
        type: 'TextNote',
        userId: 6171569,
        name: 'AKS068',
        description: null,
        tweetText: 'AKS068｜らんさぶ #note',
        twitterShareUrl: '/',
        facebookShareUrl: '/',
        lineShareUrl: '/',
        noteUrl: '/',
        canMultipleLimitedNote: false,
        canSellOnFirstComeNote: false,
        pictures: [],
        embeddedContents: [
          {
            caption: null,
            key: 'emb3d2a075e3457'
          },
          {
            caption: null,
            key: 'embd6d161f13d13'
          }
        ],
        audio: null,
        status: 'published',
        publishAt: '2024-03-02T17:07:24.000+09:00',
        price: 0,
        createdAt: '2024-03-02T12:03:24.000+09:00',
        updatedAt: '2024-03-02T17:07:24.000+09:00',
        format: '3.0',
        likeCount: 0,
        anonymousLikeCount: null,
        imageCount: 1,
        commentCount: 0,
        isLimited: false,
        isTrial: false,
        isRefund: false,
        isMembershipConnected: false,
        hasAvailableCirclePlans: false,
        isMyNote: false,
        canRead: true,
        canVote: true,
        canComment: true,
        labels: [],
        isLiked: null,
        isPurchased: false,
        isMagazinePurchased: false,
        isAvailable: false,
        eyecatch: '/img/no-image-icon.jpg',
        eyecatchWidth: 566,
        eyecatchHeight: 296,
        spEyecatch: '/img/no-image-icon.jpg',
        hasDraft: false,
        isDraft: null,
        isPublished: true,
        isReserved: false,
        reservedPublishAt: null,
        disableComment: false,
        likes: [],
        user: {
          id: 6171569,
          urlname: 'twinklestar2011',
          nickname: 'らんさぶ',
          noteCount: 273,
          followingCount: 14,
          followerCount: 17,
          userProfileImagePath: '/img/no-image-icon.jpg',
          createdAt: '2022-07-01T20:26:34.000+09:00',
          disableSupport: false,
          isFollowing: false,
          isMe: false,
          likeAppealText: null,
          likeAppealImage: null,
          shareAppeal: {
            text: '今日はいい日になりそうです',
            image: null
          },
          magazineAddAppeal: {
            text: '嬉しいです！',
            image: null
          },
          purchaseAppealTextNote: 'ありがとう、励みになります！',
          purchaseAppealTextMagazine: 'びっくりしました。ありがとうございます！',
          purchaseAppealTextSupport: '思いがけないことで、驚きでいっぱいです！',
          followAppealText: '嬉しいです。ありがとうございます！',
          followAppealImage: '/',
          twitterNickname: null,
          customDomain: null
        },
        commentViewable: true,
        comments: [],
        hashtagNotes: [],
        hasCoupon: false,
        priorSale: null,
        customDomain: null,
        editableScopes: [
          'web',
          'ios',
          'android'
        ],
        nonEditableReason: null
      },
      {
        id: 79770417,
        key: 'n9fad3be74119',
        isTreasuredNote: false,
        body: '皆さんこんにちは。\n第二回は分かる人には魅力が分かるPENTAX K-7について書いていこうと思います。\nまた、K-7をもう既に所持している方向けの情報もあるので是非 "最後まで" 見ていってください。\n\nそう、一眼レフやらフィルムやらで最近何かと話題のPENTAXです。\nそんなPENTAXでも、RICOHではなくHOYA時代のPENTAXのお話です…。\n\nPENTAX K-7とは\n\nPENTAX K-7とは、PENTAXのデジタル一眼レフカメラです。\nこのカメラのコンセプト',
        externalUrl: null,
        separator: null,
        type: 'TextNote',
        userId: 8717454,
        name: '第二回 多分PENTAXが好きなんじゃなくてK-7が好きなんだと思う',
        description: null,
        tweetText: '第二回 多分PENTAXが好きなんじゃなくてK-7が好きなんだと思う｜reflection📷 @photo7100 #note',
        twitterShareUrl: '/',
        facebookShareUrl: '/',
        lineShareUrl: '/',
        noteUrl: '/',
        canMultipleLimitedNote: false,
        canSellOnFirstComeNote: false,
        pictures: [
          {
            caption: null,
            url: '/',
            key: '1709300013680-ok8dIzALyS'
          },
          {
            caption: null,
            url: '/',
            key: '1709300171694-wvZQhnGhDR'
          },
          {
            caption: null,
            url: '/',
            key: '1709300436986-b0zFpLRNH6'
          }
        ],
        embeddedContents: [],
        audio: null,
        status: 'published',
        publishAt: '2024-03-02T17:06:19.000+09:00',
        price: 0,
        createdAt: '2024-01-29T23:10:09.000+09:00',
        updatedAt: '2024-03-02T17:06:19.000+09:00',
        format: '4.1',
        likeCount: 0,
        anonymousLikeCount: null,
        imageCount: 23,
        commentCount: 0,
        isLimited: false,
        isTrial: false,
        isRefund: false,
        isMembershipConnected: false,
        hasAvailableCirclePlans: false,
        isMyNote: false,
        canRead: true,
        canVote: true,
        canComment: true,
        labels: [],
        isLiked: null,
        isPurchased: false,
        isMagazinePurchased: false,
        isAvailable: false,
        eyecatch: '/img/no-image-icon.jpg',
        eyecatchWidth: 1280,
        eyecatchHeight: 670,
        spEyecatch: '/img/no-image-icon.jpg',
        hasDraft: false,
        isDraft: null,
        isPublished: true,
        isReserved: false,
        reservedPublishAt: null,
        disableComment: false,
        likes: [],
        user: {
          id: 8717454,
          urlname: 'photo7100',
          nickname: 'reflection📷',
          noteCount: 2,
          followingCount: 4,
          followerCount: 3,
          userProfileImagePath: '/img/no-image-icon.jpg',
          createdAt: '2024-01-05T19:15:39.000+09:00',
          disableSupport: false,
          isFollowing: false,
          isMe: false,
          likeAppealText: null,
          likeAppealImage: '',
          shareAppeal: {
            text: null,
            image: null
          },
          magazineAddAppeal: {
            text: null,
            image: null
          },
          purchaseAppealTextNote: null,
          purchaseAppealTextMagazine: null,
          purchaseAppealTextSupport: null,
          followAppealText: null,
          followAppealImage: null,
          twitterNickname: 'photo7100',
          customDomain: null
        },
        commentViewable: true,
        comments: [],
        hashtagNotes: [],
        hasCoupon: false,
        priorSale: null,
        customDomain: null,
        editableScopes: [
          'web',
          'ios',
          'android'
        ],
        nonEditableReason: null
      },
      {
        id: 81741922,
        key: 'ne34db313925a',
        isTreasuredNote: false,
        body: '現在久しぶりにメカニカルキーボードを使ってます。大分昔中華のメカニカルで、3000円台のものをAmazonで見つけたので買ってみるか～と軽い気持ちで購入しました。これが大当たり！すごくキータッチがスムーズで、キーが壊れているとかはなかった。まあ、キーがかなり軽いんでそれがミスタイプにつながることがあるなと。でも逆に疲れないんですよ。あとミスタイプはそのうち慣れてなくなります。\n\nそしてこのキーボード、87コンパクトタイプの英字キーボードなのです。そもそも私の机の上は狭いので、',
        externalUrl: null,
        separator: null,
        type: 'TextNote',
        userId: 7928496,
        name: '昔買ったメカニカルキーボードを出してきてます。',
        description: null,
        tweetText: '昔買ったメカニカルキーボードを出してきてます。｜浜田さな＠復活しました #note',
        twitterShareUrl: '/',
        facebookShareUrl: '/',
        lineShareUrl: '/',
        noteUrl: '/',
        canMultipleLimitedNote: false,
        canSellOnFirstComeNote: false,
        pictures: [],
        embeddedContents: [],
        audio: null,
        status: 'published',
        publishAt: '2024-03-02T17:05:04.000+09:00',
        price: 0,
        createdAt: '2024-03-02T16:40:31.000+09:00',
        updatedAt: '2024-03-02T17:05:04.000+09:00',
        format: '3.0',
        likeCount: 2,
        anonymousLikeCount: null,
        imageCount: 1,
        commentCount: 0,
        isLimited: false,
        isTrial: false,
        isRefund: false,
        isMembershipConnected: false,
        hasAvailableCirclePlans: false,
        isMyNote: false,
        canRead: true,
        canVote: true,
        canComment: true,
        labels: [],
        isLiked: null,
        isPurchased: false,
        isMagazinePurchased: false,
        isAvailable: false,
        eyecatch: '/img/no-image-icon.jpg',
        eyecatchWidth: 1918,
        eyecatchHeight: 1004,
        spEyecatch: '/img/no-image-icon.jpg',
        hasDraft: false,
        isDraft: null,
        isPublished: true,
        isReserved: false,
        reservedPublishAt: null,
        disableComment: false,
        likes: [],
        user: {
          id: 7928496,
          urlname: 'sanahama',
          nickname: '浜田さな＠復活しました',
          noteCount: 387,
          followingCount: 120,
          followerCount: 63,
          userProfileImagePath: '/img/no-image-icon.jpg',
          createdAt: '2023-07-20T06:19:19.000+09:00',
          disableSupport: false,
          isFollowing: false,
          isMe: false,
          likeAppealText: 'スキありがとうございます！エネルギーになります！！',
          likeAppealImage: '/',
          shareAppeal: {
            text: null,
            image: null
          },
          magazineAddAppeal: {
            text: null,
            image: null
          },
          purchaseAppealTextNote: null,
          purchaseAppealTextMagazine: null,
          purchaseAppealTextSupport: null,
          followAppealText: 'よければ続けて見てください☆',
          followAppealImage: '/',
          twitterNickname: null,
          customDomain: null
        },
        commentViewable: true,
        comments: [],
        hashtagNotes: [],
        hasCoupon: false,
        priorSale: null,
        customDomain: null,
        editableScopes: [
          'web',
          'ios',
          'android'
        ],
        nonEditableReason: null
      },
      {
        id: 81719551,
        key: 'n724b8ebb8527',
        isTreasuredNote: false,
        body: '昨年秋に、念願だったフルサイズ一眼レフカメラ「CANON EOS 6D」をオークションで格安で手に入れました。\n\n落札価格はなんと定価の4分の1以下！！！！\nオークションバトルの戦利品として自己満足度高めの一品です(笑)\n\n見た目の程度もよく、基本的な動作にはまったく問題は感じません。\nこれはいい買い物をしたと喜んでいたのですが、少し前からちょっと気になる挙動が・・・\n\nSDカードの読み込みエラーが多発する！？\n\n別のSDカードを数枚試したものの、やはり認識してくれず・・・ど',
        externalUrl: null,
        separator: null,
        type: 'TextNote',
        userId: 4711872,
        name: 'USBメモリやSDカード・・・接触不良はこれ一本で解決！',
        description: null,
        tweetText: 'USBメモリやSDカード・・・接触不良はこれ一本で解決！｜オカベ ヤスユキ〈国家資格キャリアコンサルタント｜CDA｜コミュニケーションファシリテーター〉 @okatin16 #note',
        twitterShareUrl: '/',
        facebookShareUrl: '/',
        lineShareUrl: '/',
        noteUrl: '/',
        canMultipleLimitedNote: false,
        canSellOnFirstComeNote: false,
        pictures: [
          {
            caption: null,
            url: '/',
            key: '1709339759260-8sPMaS7KxZ'
          },
          {
            caption: null,
            url: '/',
            key: '1709339881098-3hX4ikhrIO'
          },
          {
            caption: null,
            url: '/',
            key: '1709366579538-KOkGa7BDtA'
          },
          {
            caption: null,
            url: '/',
            key: '1709339835579-eouedPzYa2'
          }
        ],
        embeddedContents: [
          {
            caption: null,
            key: 'emb8a247a14c99d'
          },
          {
            caption: null,
            key: 'emb7165f9df84fb'
          },
          {
            caption: null,
            key: 'emb5c045f1ae0ed'
          }
        ],
        audio: null,
        status: 'published',
        publishAt: '2024-03-02T17:04:50.000+09:00',
        price: 0,
        createdAt: '2024-03-02T09:02:48.000+09:00',
        updatedAt: '2024-03-02T17:04:50.000+09:00',
        format: '4.0',
        likeCount: 0,
        anonymousLikeCount: null,
        imageCount: 5,
        commentCount: 0,
        isLimited: false,
        isTrial: false,
        isRefund: false,
        isMembershipConnected: false,
        hasAvailableCirclePlans: false,
        isMyNote: false,
        canRead: true,
        canVote: true,
        canComment: true,
        labels: [],
        isLiked: null,
        isPurchased: false,
        isMagazinePurchased: false,
        isAvailable: false,
        eyecatch: '/img/no-image-icon.jpg',
        eyecatchWidth: 1920,
        eyecatchHeight: 1005,
        spEyecatch: '/img/no-image-icon.jpg',
        hasDraft: false,
        isDraft: null,
        isPublished: true,
        isReserved: false,
        reservedPublishAt: null,
        disableComment: false,
        likes: [],
        user: {
          id: 4711872,
          urlname: 'okatin',
          nickname: 'オカベ ヤスユキ〈国家資格キャリアコンサルタント｜CDA｜コミュニケーションファシリテーター〉',
          noteCount: 1007,
          followingCount: 24,
          followerCount: 71,
          userProfileImagePath: '/img/no-image-icon.jpg',
          createdAt: '2021-05-31T23:39:34.000+09:00',
          disableSupport: false,
          isFollowing: false,
          isMe: false,
          likeAppealText: 'とってもうれしかったです♪',
          likeAppealImage: null,
          shareAppeal: {
            text: 'シェアしてくださってうれしいです💕',
            image: null
          },
          magazineAddAppeal: {
            text: null,
            image: null
          },
          purchaseAppealTextNote: null,
          purchaseAppealTextMagazine: null,
          purchaseAppealTextSupport: null,
          followAppealText: 'フォローありがとうございます♪',
          followAppealImage: null,
          twitterNickname: 'okatin16',
          customDomain: null
        },
        commentViewable: true,
        comments: [],
        hashtagNotes: [],
        hasCoupon: false,
        priorSale: null,
        customDomain: null,
        editableScopes: [
          'web',
          'ios',
          'android'
        ],
        nonEditableReason: null
      }
    ]
  }
}

/** 空の記事データ */
export const emptyData: NoteTechArticleResponse = {
  data: {
    categoryId: 1,
    firstPage: true,
    nextPage: 2,
    lastPage: false,
    notes: []
  }
}
