name: CI/CD Pipeline (Build & Test)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.1]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Build (and Type Check)
        run: npm run build
      - name: Run lint
        run: npm run lint
      - name: Run Unit Test
        run: npm run test:ut
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run VRT tests
        run: npm run test:vrt
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
