name: CI/CD Pipeline (VRT With Playwright)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  vrt-with-playwright:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.1-jammy
    strategy:
      matrix:
        node-version: [20.11.1]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run VRT Build
        run: npm run build:vrt
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chrome msedge
      - name: Run VRT tests
        run: HOME=/root npm run test:vrt
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
